Add wiring instructions to the quick start guide
Annex-Engineering/Belay pull request #1
Opened 2024-08-25 17:16 UTC by thePunderWoman

This adds some instructions on how to wire the belay for users, like myself, who may be new to wiring, controller boards, and klipper.

Note:
I took a photo of the Octopus v1.1 pointing at the port I used, but I wasn't sure if it would help or hurt. Let me know what you think and I can add that in with a "This photo illustrates an example of the endstop port on a controller board, in this case an Octopus v1.1".

2024-08-25 23:52 UTC, rsghosh requested changes
Thanks! This looks great overall, I just left a few very minor suggested changes.

I think it is fine without the photo of the Octopus, since the endstop port location will depend on the board being used and should be explained by the board's documentation.

2024-08-25 23:52 UTC, rsghosh commented on docs/Quick_Start.md
> +The wires will not be used to carry voltage. So you don't have to worry about using a specific guage of wire.
```suggestion
The wires will not be used to carry any substantial current, so you don't have to worry about using a specific gauge of wire.
```

2024-08-25 23:52 UTC, rsghosh commented on docs/Quick_Start.md
> +Next, you'll need to identify a port on your controller board you want to use. An endstop port is the easiest option, but you can use whatever is open. Make sure you note the sensor pin id of this po
```suggestion
Next, you'll need to identify a port on your controller board to use. An endstop port is the easiest option, but you can use almost any available port with an input signal pin and a ground pin. Make sure you note the microcontroller pin name for the signal pin of this port, as you'll need it when we get to setting up the belay in Klipper later. In this example, we'll be using an endstop port. This is a 3-pin port, and connects using a JST-XH connector.
```

2024-08-25 23:52 UTC, rsghosh commented on docs/Quick_Start.md
> +That's all it takes to wire the belay. Whenever you're ready, you can run the wire and plug it in to your printer's controller board. Remember that sensor pin id for the next steps.
```suggestion
That's all it takes to wire the belay. Whenever you're ready, you can run the wire and plug it in to your printer's controller board. Remember that sensor pin name for the next steps.
```

2024-08-26 13:41 UTC, thePunderWoman commented on docs/Quick_Start.md
> +The wires will not be used to carry voltage. So you don't have to worry about using a specific guage of wire.
Updated!

2024-08-26 13:41 UTC, thePunderWoman commented on docs/Quick_Start.md
> +Next, you'll need to identify a port on your controller board you want to use. An endstop port is the easiest option, but you can use whatever is open. Make sure you note the sensor pin id of this po
Updated

2024-08-26 13:41 UTC, thePunderWoman commented on docs/Quick_Start.md
> +That's all it takes to wire the belay. Whenever you're ready, you can run the wire and plug it in to your printer's controller board. Remember that sensor pin id for the next steps.
Aaaaand updated.

2024-08-26 23:32 UTC, merged